### ISSUE TITLE
cannot query events - forbidden

### ISSUE THREAD

**Issue by spaniard-usa** [secureworks/taegis-sdk-python#3]
Installed the SDK and I am able to query alerts, assets, investigations, users... but have not been able to query events.
Using the sample script available in the docs (https://github.com/secureworks/taegis-sdk-python/blob/main/docs/querying_events.md)  --tried both delta and US2 environments.

Let me know what else I can try.  Will keep poking around in the mean time.

Thanks!

script response below.

`

> Traceback (most recent call last):
>   File "/home/jorge/Taegis/./events.py", line 15, in <module>
>     results = service.events.subscription.event_query("FROM process EARLIEST=-1d | head 10", options=options)
>   File "/home/jorge/.local/lib/python3.10/site-packages/taegis_sdk_python/services/events/subscriptions.py", line 41, in event_query
>     result = self.service.execute_subscription(
>   File "/home/jorge/.local/lib/python3.10/site-packages/taegis_sdk_python/service_core.py", line 178, in execute_subscription
>     graphql_field = self.get_ws_schema().subscription_type.fields.get(endpoint)
>   File "/home/jorge/.local/lib/python3.10/site-packages/taegis_sdk_python/utils.py", line 142, in wrapper
>     result = future.result()
>   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
>     return self.__get_result()
>   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
>     raise self._exception
>   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/home/jorge/.local/lib/python3.10/site-packages/taegis_sdk_python/utils.py", line 138, in run_async
>     return asyncio.run(coro(*args, **kwargs))
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
>     return future.result()
>   File "/home/jorge/.local/lib/python3.10/site-packages/taegis_sdk_python/service_core.py", line 117, in get_ws_schema
>     async with client:
>   File "/home/jorge/.local/lib/python3.10/site-packages/gql/client.py", line 658, in __aenter__
>     return await self.connect_async()
>   File "/home/jorge/.local/lib/python3.10/site-packages/gql/client.py", line 632, in connect_async
>     await self.transport.connect()
>   File "/home/jorge/.local/lib/python3.10/site-packages/gql/transport/websockets_base.py", line 490, in connect
>     self.websocket = await asyncio.wait_for(
>   File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
>     return fut.result()
>   File "/usr/lib/python3.10/asyncio/tasks.py", line 650, in _wrap_awaitable
>     return (yield from awaitable.__await__())
>   File "/home/jorge/.local/lib/python3.10/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
>     return await self.__await_impl__()
>   File "/home/jorge/.local/lib/python3.10/site-packages/websockets/legacy/client.py", line 662, in __await_impl__
>     await protocol.handshake(
>   File "/home/jorge/.local/lib/python3.10/site-packages/websockets/legacy/client.py", line 329, in handshake
>     raise InvalidStatusCode(status_code, response_headers)
> websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 403

`

**Comment by mpegman-scwx** [comment]
Hello @spaniard-usa ,

From the looks of your error message, the API call seems to be failing at the introspection layer.  The SDK queries the gateway for a schema to help build and validate before sending your specific call to the server.  This would not be a failing on any implementation of your code or the SDK.

I have tried this code segment with both "delta" and "US2" with a number of different roles without issue:

```
from taegis_sdk_python.services import GraphQLService
from taegis_sdk_python.services.events.types import EventQueryOptions

service = GraphQLService(environment="US2")
options = EventQueryOptions(
    timestamp_ascending=True,
    page_size=1000,
    max_rows=1000,
    skip_cache=True,
    aggregation_off=False,
)

results = service.events.subscription.event_query(
    """
    FROM process EARLIEST=-1d | head 10
    """,
    options=options
)
print(results)
```

If you are still receiving the error, can you open a ticket with Taegis product support so we can look at your account and user specifics?

**Comment by spaniard-usa** [comment]
Just opened a ticket through Taegis support. :)

**Comment by mpegman-scwx** [comment]
@spaniard-usa I was finally able to replicate the issue on my end.  I believe I have found the issue and released a fix in v1.0.0-alpha9, could you update the sdk package and try the events search again?

I am removing the `x-tenant-context-xxxxx` Sec-WebSocket-Protocol header when a tenant_id is not explicitly set.  That fixed it in my replication test.

I appreciate your patience and assistance in tracking this issue.

**Comment by spaniard-usa** [comment]
:) Test was successful with 1.0.0a9.
Thank you for the help!!

**Comment by AkechiShiro** [comment]
I ran into this issue as well, I thought that a `tenant_id` was necessary not optional so that this API call would be allowed.

But it seems it was not needed, thanks for reporting the issue @spaniard-usa
