### ISSUE TITLE
The token get function always gets client_id and client_secret from env variables regardless data saved in the config file

### ISSUE THREAD

**Issue by denven** [secureworks/taegis-sdk-python#6]
issued code: `taegis_sdk_python/authentication.py`

Once the `client_id_env_var` and `client_secret_env_var` are read from the `config` file written by `write_to_config`, the code still reads the `client_id` and `client_secret` from system env variables.

This will result in the access token can't be granted since the `client_id` and `client_secret` can not be returned with values once the env variables are not set before hand. The code will always prompt you to input the Username to authenticate.

```python
def get_oauth_from_env(environment: str) -> Tuple[Optional[str], Optional[str]]:
    ...
    config = get_config()
    client_id_env_var = config.get(environment, "CLIENT_ID", fallback="CLIENT_ID")
    client_secret_env_var = config.get(
        environment, "CLIENT_SECRET", fallback="CLIENT_SECRET"
    )

    client_id = os.environ.get(client_id_env_var)
    client_secret = os.environ.get(client_secret_env_var)

    return client_id, client_secret

```

**Comment by mpegman-scwx** [comment]
Can you help me with understanding the use case?

This code is meant to support the following:

```python
write_to_config("charlie", "CLIENT_ID", "CHARLIE_CLIENT_ID")
write_to_config("charlie", "CLIENT_SECRET", "CHARLIE_CLIENT_SECRET")
```

In your shell outside of the script:
```
export CHARLIE_CLIENT_ID="<your_client_id>"
export CHARLIE_CLIENT_SECRET="<your_client_secret>"
```

Then 
```python
service = GraphQLService(environment="charlie")
results = service.subjects.query.current_subject()
```

This will result in the SDK authenticating to charlie only using the specified "<your_client_id>" and "<your_client_secret>" values.  The write_to_config only changes the environment variable reference and should not store the actual values.  Logins to delta/echo/foxtrot will continue to use the CLIENT_ID and CLIENT_SECRET environment variables unless also configured.

Secrets should not be committed to code or files and should be stored in an encrypted vault.

**Comment by denven** [comment]
> Can you help me with understanding the use case?
> 
> This code is meant to support the following:
> 
> ```python
> write_to_config("charlie", "CLIENT_ID", "CHARLIE_CLIENT_ID")
> write_to_config("charlie", "CLIENT_SECRET", "CHARLIE_CLIENT_SECRET")
> ```
> 
> In your shell outside of the script:
> 
> ```
> export CHARLIE_CLIENT_ID="<your_client_id>"
> export CHARLIE_CLIENT_SECRET="<your_client_secret>"
> ```
> 
> Then
> 
> ```python
> service = GraphQLService(environment="charlie")
> results = service.subjects.query.current_subject()
> ```
> 
> This will result in the SDK authenticating to charlie only using the specified "<your_client_id>" and "<your_client_secret>" values. The write_to_config only changes the environment variable reference and should not store the actual values. Logins to delta/echo/foxtrot will continue to use the CLIENT_ID and CLIENT_SECRET environment variables unless also configured.
> 
> Secrets should not be committed to code or files and should be stored in an encrypted vault.

For now, I understand the purpose of the function `write_to_config` and why the code is written like that. It is not used to write an environment variable and its value into a config file but to define the `client_id` and `client_secret` environment variable names. I misunderstood the usage of this function due to its naming and sample code😕 .

Thanks for your reply and you can close the issue.

**Comment by mpegman-scwx** [comment]
Thanks for the interest!  It's a complicated feature meant for developers that need access to multiple Taegis regions on the same server and need to submit different client credentials on each.  We have an upcoming feature in Taegis to abstract the needed region that should reduce this confusion.
